### ISSUE TITLE
Generalize common steps?

### ISSUE THREAD

**Issue by nicholasdille** [nicholasdille/packages#10]
- [x] Get latest tag from GitHub
- [x] Filter assets by full name
- [x] Filter assets by suffix
- [x] Filter assets by prefix
- [x] Install binary and set executable bits
- [x] Unpack tarball
- [x] Unpack zip
- [x] ~Build containerized~ (moved to #24)
- [x] ~Install to staging directory~
- [x] ~Install from staging to target directory~
- [x] Check sudo before installation
- [x] Implemented chaining filters
- [x] Implemented running multiple installations from one release
- [x] ~github_install: Determine type from name~
- [x] github_find_latest_release: Print version
- [x] untar_file: Support for `--strip-components`
- [x] ~untar_file: Support for targets (`${TARGET_BIN}` vs. `${TARGET_BASE}`)~ (moved to #47)
- [x] github_install: Support for new type `gzip` (e.g. `cheat`, `tig`)
- [x] github_install: Parameter `name` only for type `binary`
- [x] ~github_install: Support for multiple matchers (e.g. `crictl`)?~ (moved to #48)
- [x] ~github_install: Support for multiple installations from one release (e.g. `cfssl`)~ (moved to #48)

**Comment by nicholasdille** [comment]
Use web pages #17
