### ISSUE TITLE
Test all packages

### ISSUE THREAD

**Issue by nicholasdille** [nicholasdille/packages#604]
Status: Done up to and including `lab`

Issues:

- [x] Fix python
- [x] Fix ruby
- [x] ~Fix runq~ (see #372)
- [x] Fix shellspec (requires `make`)
- [x] Fix wslu (requires `make`)
- [x] ~Fix sysbox (requires `make` and more ;-))~ (see #460)
- [x] ~Fix skopeo (unknown make target `bin/skopeo`)~ (see #616)
- [x] Test python packages with docker
- [x] ~lazydocker: Version is incorrectly extracted by `pkgctl.sh` (works locally)~ (see #617)

```
cat packages.json | jq -r '.packages[].name' | tail -n +94 | while read PACKAGE; do echo "### ${PACKAGE}"; if ! bash te
st.sh ${PACKAGE}; then break; fi; done
```
